### ISSUE TITLE
Invalid encoding when running a specific executable on Windows

### ISSUE THREAD

**Issue by mtaku3** [Tyrrrz/CliWrap#196]
### Version

ver 3.6.0

### Details

Some executables varies its output encoding based on the console's default encoding. CliWrap offers a feature to change an encoding of the standard output stream reader. But it never changes the console's default encoding, so there's possibility that the characters being garbled.
.NET's Process class can change the console's default encoding at [`ProcessStartInfo.StandardOutputEncoding`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.standardoutputencoding?view=net-7.0).
Reproduction code tries to echo a character `ϧ` (U+03E7).
[`CliWrapImpl`](https://github.com/mtaku3/CliWrapEncodingIssue/blob/fd6168a36dcb084ff0397f109b780864aa8744af/Program.cs#L21-L26) will read the output in console's default encoding, so that the character will be garbled.
[`DotNetImpl`](https://github.com/mtaku3/CliWrapEncodingIssue/blob/fd6168a36dcb084ff0397f109b780864aa8744af/Program.cs#L28-L47) will read the output in the UTF-8 encoding because it's specified at [`ProcessStartInfo.StandardOutputEncoding`](https://github.com/mtaku3/CliWrapEncodingIssue/blob/fd6168a36dcb084ff0397f109b780864aa8744af/Program.cs#LL38C5-L38C5), so that the character will *not* be garbled.
.NET Console Application's default encoding is the same as the console's default encoding so that the character may still be garbled. ([`Console.OutputEncoding`](https://learn.microsoft.com/en-us/dotnet/api/system.console.outputencoding?view=net-7.0) must be the same as [`chcp`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chcp#:~:text=If%20used%20without%20parameters%2C%20chcp%20displays%20the%20number%20of%20the%20active%20console%20code%20page.) on cmd)
But you can find that `ProcessStartInfo.StandardOutputEncoding` can change the console's default encoding on the process and it prevents the characters being consumed in the wrong encoding.

### Steps to reproduce

Reproduction code is [here](https://github.com/mtaku3/CliWrapEncodingIssue).
Just clone, build and run it.
One thing to notice is that console's default encoding varies based on the system locale according to a [Microsoft's arcticle](https://learn.microsoft.com/en-us/previous-versions/aa912040(v=msdn.10)?redirectedfrom=MSDN). So the behavior may vary as well. Please let me know if you couldn't reproduce this.

**Comment by Tyrrrz** [comment]
Hey @mtaku3.

I was able to reproduce the discrepancy with your help, thank you. I'm now trying to figure out whether this is a bug and how to address it.

Furthermore, I tried to replicate your scenario in CliWrap tests (which are running against a .NET executable instead of a batch file) and it didn't work. It seems that `ProcessStartInfo.StandardOutputEncoding` does not have any effect on certain type of programs – or at least .NET console applications.

I also tried to dig through the documentation to see whether this is an edge case or an OS-specific behavior but I was not able to find any official information regarding this scenario. The docs you linked (https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.standardoutputencoding?view=net-7.0) don't provide a lot of useful information beyond this remark:

> Setting this property does not guarantee that the process will use the specified encoding. The application should be tested to determine which encodings the process supports.

Question: does your original use case also involve a batch file? If not, what kind of program is it?

**Comment by Tyrrrz** [comment]
As an immediate workaround, you can use this extension method:

```csharp
public static Command WithChcpWrapper(this Command command, Encoding encoding)
{
    return Cli.Wrap("cmd")
        .WithArguments(a => a
            .Add("/c")
            .Add($"chcp {encoding.CodePage}")
            .Add(">nul")
            .Add("&&")
            .Add(command.TargetFilePath)
            .Add(command.Arguments, false)
        )
        .WithWorkingDirectory(command.WorkingDirPath)
        .WithEnvironmentVariables(command.EnvironmentVariables)
        .WithCredentials(command.Credentials)
        .WithStandardInputPipe(command.StandardInputPipe)
        .WithStandardOutputPipe(command.StandardOutputPipe)
        .WithStandardErrorPipe(command.StandardErrorPipe)
        .WithValidation(command.Validation);
}
```

It wraps your existing command in `cmd` and sets the encoding within that session. You can use it like so:

```csharp
private static async Task CliWrapImpl()
{
    await Cli.Wrap("echo.bat")
        .WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine, Encoding.UTF8))
        .WithChcpWrapper(Encoding.UTF8)
        .ExecuteBufferedAsync();
}
```

Note that I removed `./` from the path because `cmd` trips up on paths starting with `.` unless they're quoted, and CliWrap doesn't quote `.` because it's not considered a special character. You may want to tweak it a bit.

**Comment by Tyrrrz** [comment]
I'm not entirely sure how to solve this for the general case in CliWrap, given the fact that pipes are logically detached from the process and the fact that a command can have multiple outbound pipes (with different encodings) at once. I think, ultimately, encoding should be moved from `ExecuteBufferedAsync()`/`PipeTarget.ToDelegate(...)`/etc overloads to core command configuration.

However, considering the fact that specifying encoding through `ProcessStartInfo` seems very inconsistent, I'm not too confident about relying on this behavior. I'm also not sure if this works at all on other operating systems (I know `chcp` doesn't, but not sure about `ProcessStartInfo.StandardOutputEncoding`). At the moment, I'm currently more keen to recommend using the `chcp` workaround shown above instead of making significant design changes in the library.

**Comment by Tyrrrz** [comment]
Actually, after further testing, it seems that even making this change is enough to get it working. Can you test it out @mtaku3?

```diff
private static async Task CliWrapImpl()
{
    await Cli.Wrap("./echo.bat")
-        .WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine))
+        .WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine, Encoding.UTF8))
        .ExecuteAsync();
}
```

**Comment by mtaku3** [comment]
I was in a wrong way. You are right!
I was doing like this
```csharp
Cli.Wrap("./example.exe")
	.WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine))
	.Observe(Encoding.UTF8, Encoding.UTF8, forciblyCloseCTS.Token, gracefullyCloseCTS.Token)
	.Subscribe();
```
But I didn't notice that encoding parameters on Observe() has an effect only on the observable, which will be created by Observe() and it doesn't have an effect on Pipe which is merged by WithStandardOutputPipe().
Providing Encoding.UTF8 in WithStandardOutputPie solved my issue.

For your reference, I was trying to run a process made of Go and is using log package for logging. log package doesn't have a feature to set the encoding and seems to depend on the console.

Also, I tested with another batch file, which outputs the current code page by `chcp` and run it on CliWrapImpl and DotNetImpl. Both of it outputs the same encoding and looks like both of it doesn't have an effect on the console's encoding. So to change the console's encoding, I have to use something like your `WithChcpWrapper`.

Thank you.
