### ISSUE TITLE
Support async binary output and input streams

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/CliWrap#25]
Example of binary pipeline stream:
https://gist.github.com/SlowLogicBoy/45f25b3711c341ba974fe22f04f71f4a
Multiple pipelines example:
https://gist.github.com/SlowLogicBoy/63037d655cf8c667ae09ccebcf1164aa

**Comment by stil** [comment]
Hi,
First of all, thanks for making this library. It's well designed and solves my 80% use cases when working with cli tools.

But I'd really like to have support for binary stdout and stderr.

Can we make it possible? Instead of using `StringBuilder`, and `OutputDataReceived`/`ErrorDataReceived` we can use `Stream.CopyToAsync()` on stdout/stderr streams and copy them to `MemoryStream`.

Then allow users access it either directly from ExecutionOutput class or through convenience method that would lazily convert it to encoded string (doing it lazily could improve performance a bit).

There is a problem with `OutputDataReceived`/`ErrorDataReceived` that it eats either `\r\n`, `\r` or `\n` and you can't guess which one it was.  I think we should abandon using this API in favor of streams.

Also, maybe make it possible to specify your own target streams?

**Comment by Tyrrrz** [comment]
I'm definitely also interested in supporting binary stdin/stdout, so I'm sure this will get implemented in one shape or form.

**Comment by stil** [comment]
How about we use `System.IO.Pipelines` and expose PipeWriter for stdin and PipeReader for both stdout and stderr as public API? Pipelines have much cleaner API than direct operations on streams.

**Comment by Tyrrrz** [comment]
Examples and pull requests are welcome :)

**Comment by SlowLogicBoy** [comment]
I just added example with multiple pipes.

**Comment by Tyrrrz** [comment]
Sweet!

**Comment by Tyrrrz** [comment]
Binary stdin has recently been implemented.

**Comment by Tyrrrz** [comment]
@stil 
I remember that originally CliWrap was reading directly from streams, instead of using events, but there were some cases where that led to deadlocks.

**Comment by Tyrrrz** [comment]
This is now implemented.
@stil

**Comment by stil** [comment]
@Tyrrrz this looks great, I'll definitely give it a try.
