### ISSUE TITLE
Passing List<string> as arguments produces random quotes(")

### ISSUE THREAD

**Issue by maeneak** [Tyrrrz/CliWrap#51]
Not sure if this is a bug or by design. But even using the builder method produces the same results.

**Comment by Tyrrrz** [comment]
Hi.

The quotes are added to escape special characters (mostly spaces) in the arguments so that the target executable treats them exactly as you typed them. This is by design.

For example, say you do this:

```csharp
Cli.Wrap("foo").WithArguments(new[] {"--option-a", "value", "--option-b", "value with space"});
```

The arguments will get formatted into `--option-a value --option-b "value with space"` to make sure `value with space` is treated as a single argument instead of three.
