### ISSUE TITLE
System.InvalidOperationException: No process is associated with this object.

### ISSUE THREAD

**Issue by prcdpr** [Tyrrrz/CliWrap#73]
I'm getting `System.InvalidOperationException` while trying to start the process.

```
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at CliWrap.Internal.ProcessEx.Dispose()
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken cancellationToken)
```

What it actually means is that `targetFilePath` pointed to non-existing exe and the process didn't even start. Which is fine, but it throws an exception in wrong place and the exception message is misleading.

Could we have a check whether the process actually started?

**Comment by Tyrrrz** [comment]
I think this issue is a bit more specific. What OS are you using?
In some cases the error would appear when running the application without required permissions (on Linux).

**Comment by prcdpr** [comment]
I'm using Windows 10, I've got this error while trying to call exe from xunit tests project in Rider. It's probably unrelated, but when I added the missing .exe to directory, it worked.

**Comment by Tyrrrz** [comment]
Ok thanks. The fix is already in master (hasn't been released yet), I'm just trying to gather more info to figure out when it happens so that the library can provide a better error message.

**Comment by g3rv4** [comment]
chiming in here because I've just fixed it on my project. Here are some details on my scenario:

* Using MacOS
* Want to execute "open /path/to/package.pkg" to run an uninstaller (if I try to "open Firefox" for instance, everything works fine)
* Only breaks if signed with hardened runtime (required for notarization)

And the fix in my case was to add the `com.apple.security.cs.allow-dyld-environment-variables` entitlement.

**Comment by fotijr** [comment]
I got this error on Linux. It turned out to be a configuration issue in my app- the path passed to `WithWorkingDirectory()` didn't exist on the machine. Easy fix once I discovered the configuration issue, but if the error message was cleaner it would've saved me a lot of time. This is probably outside of this library's scope, but just adding here so you have more possible causes.

Huge fan of the library, thank you and great work!

**Comment by Tyrrrz** [comment]
It should already provide clearer error messages, at least when related to the process resource acquisition issue (as mentioned in OP). Unfortunately, it's really hard to handle these type of exceptions because they don't provide extra information and they all have the same type.
