### ISSUE TITLE
Running "git clone" command does not get the full output

### ISSUE THREAD

**Issue by Rwing** [Tyrrrz/CliWrap#87]
For example, running "git clone https://github.com/Tyrrrz/CliWrap.git" in shell will get above ouput:

> Cloning into 'CliWrap'...
> remote: Enumerating objects: 1592, done.
> Receiving objects:  98% (1561/1592), 308.01 KiB | 10.00 KiB/s   592
> Receiving objects: 100% (1592/1592), 320.52 KiB | 10.00 KiB/s, done.
> Resolving deltas: 100% (977/977), done.
> Checking connectivity... done.

But in CliWrap only get one line ouput, I tried ExecuteBufferedAsync and ListenAsysnc.

> Cloning into 'CliWrap'...

I think the reason might be that "git.exe" is calling another program "git-clone.exe".  
So is there any solution to solve it?

**Comment by Rwing** [comment]
Okay, I think this is a git feature when I found this article.
https://stackoverflow.com/questions/35700994/how-to-capture-git-clone-output-with-fork-exec

But I had another problem, the all progress info in one StandardErrorCommandEvent like this :
> Receiving objects: 1%
> Receiving objects: 2%
> ...
> Receiving objects: 100%

Is there any way allow the output line by line in multiple events ?

**Comment by Tyrrrz** [comment]
If I had to guess, git probably writes progress status to stderr, not stdout.
As for your second question, `StandardErrorCommandEvent` is produced when the output contains a linebreak. It might be that git just updates progress by resetting the caret without actually writing a new line character. That issue is tracked here: #66. There's also a workaround here: #71.
